### ISSUE TITLE
Cargar datos y elaborar reporte

### ISSUE THREAD

**Issue by DrJoseGallardo** [duncanrosalessch/duncanrosales#1]
Estimado Duncan,

Favor cargar datos y elaborar reporte para poder entregar nuestra retroalimentación.

Saludos

**Comment by DrJoseGallardo** [comment]
Estimado Duncan,

Necesitamos que avances en tu proyecto para poder entregar nuestra retroalimentación.

Saludos

**Comment by duncanrosalessch** [comment]
> Estimado Duncan,
> 
> Necesitamos que avances en tu proyecto para poder entregar nuestra retroalimentación.
> 
> Saludos

Estimado profesor, se encuentra cargada base de datos.  Lo hice sobre datos de fito para un CIMAR FIORDO en un área de interés acuícola.  Tenía datos productivos para centros de cultivo, pero ahora decidí no me eran del todo útiles.

Saludos
